group=com.jauntsdn.rsocket
version=1.6.0

googleJavaFormatPluginVersion=0.9
dependencyManagementPluginVersion=1.1.0
protobufPluginVersion=0.8.19
gitPluginVersion=0.13.0
osDetectorPluginVersion=1.7.3

rsocketVersion=1.6.0
slf4jVersion=1.7.36
logbackVersion=1.2.13
grpcVersion=1.75.0
jacksonVersion=2.20.0
reactorNettyVersion=1.2.10

org.gradle.parallel=true
org.gradle.configureondemand=true